spring.application.name=FixKart
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://100.108.184.127:5432/UAT_FIXKART
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#debug=true
#server.port=8081

# 15 days
jwt.secret=31203fea8bcfa0f2ea8387396d6207c9
jwt.expiration=1296000000 

# photo / file upload directory

file.upload-dir=uploads/